import { ModuleDefinition } from '../../types/modules.ts';

export const EDTECH_MODULES: ModuleDefinition[] = [
  {
    id: 'question-bank',
    numericIndex: 1,
    name: 'Question Bank',
    category: 'Assessment',
    phase: 'Phase 1 (Foundation)',
    description: 'Centralized repository of categorized questions with LaTeX/image support, taxonomy tags, answer keys, and difficulty levels.',
    prismaModels: ['Subject', 'Topic', 'Question'],
    primaryApiRoutes: ['/api/v1/questions', '/api/v1/subjects', '/api/v1/topics'],
    primaryActors: ['ADMIN', 'TEACHER'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Questions cannot be permanently deleted if linked to existing exam submissions',
      'Correct answers and explanations are stripped from client payloads during student fetch',
      'Supports single-choice, multi-choice, numerical, and true/false types',
    ],
  },
  {
    id: 'practice-system',
    numericIndex: 2,
    name: 'Practice System',
    category: 'Assessment',
    phase: 'Phase 2 (Assessment & Tracking)',
    description: 'Self-paced learning drills with instant feedback, solution hints, untimed exploration, and adaptive difficulty progression.',
    prismaModels: ['PracticeSession', 'PracticeAnswer'],
    primaryApiRoutes: ['/api/v1/practice/start', '/api/v1/practice/submit', '/api/v1/practice/history'],
    primaryActors: ['STUDENT'],
    mobileTarget: 'Offline-First',
    keyInvariants: [
      'Students can review answers immediately with full pedagogical explanations',
      'Supports offline caching of practice sets with batch sync upon reconnection',
      'Does not penalize scores with negative marking',
    ],
  },
  {
    id: 'online-examination',
    numericIndex: 3,
    name: 'Online Examination',
    category: 'Assessment',
    phase: 'Phase 2 (Assessment & Tracking)',
    description: 'High-integrity scheduled examinations with server-authoritative timer, auto-submission, negative marking, and tab-switch monitoring.',
    prismaModels: ['Exam', 'ExamBatch', 'ExamQuestion', 'ExamSubmission', 'ExamAnswer'],
    primaryApiRoutes: ['/api/v1/exams', '/api/v1/exams/:id/start', '/api/v1/exams/:id/heartbeat', '/api/v1/exams/:id/submit'],
    primaryActors: ['ADMIN', 'TEACHER', 'STUDENT'],
    mobileTarget: 'Online Real-Time',
    keyInvariants: [
      'Server-authoritative timer: client elapsed time is verified against startedAt timestamp on server',
      'Auto-submits when duration + 60s grace period is exceeded',
      'Monitors tab switches and flags suspicious sessions exceeding threshold',
    ],
  },
  {
    id: 'student-management',
    numericIndex: 4,
    name: 'Student Management',
    category: 'Academic Core',
    phase: 'Phase 1 (Foundation)',
    description: 'Comprehensive student directory, admission indexing, enrollment histories, guardian linkages, and lifecycle status.',
    prismaModels: ['StudentProfile', 'GuardianProfile', 'User'],
    primaryApiRoutes: ['/api/v1/students', '/api/v1/students/:id', '/api/v1/students/import'],
    primaryActors: ['ADMIN', 'TEACHER', 'SUPER_ADMIN'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Every student is mapped to a unique admission number and system identity',
      'Deletion cascades into profiles but maintains historical exam integrity logs',
    ],
  },
  {
    id: 'batch-management',
    numericIndex: 5,
    name: 'Batch Management',
    category: 'Academic Core',
    phase: 'Phase 1 (Foundation)',
    description: 'Academic cohort and class management, term schedules, mentor assignments, and student roster enrollments.',
    prismaModels: ['Batch', 'BatchEnrollment', 'StaffBatchAssignment'],
    primaryApiRoutes: ['/api/v1/batches', '/api/v1/batches/:id/enroll', '/api/v1/batches/:id/roster'],
    primaryActors: ['ADMIN', 'SUPER_ADMIN', 'TEACHER'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'A student can belong to multiple batches (e.g. Regular 2026 + Olympiad Prep)',
      'Batches define scheduling windows for exams and attendance registers',
    ],
  },
  {
    id: 'student-performance',
    numericIndex: 6,
    name: 'Student Performance',
    category: 'Analytics & Habits',
    phase: 'Phase 3 (Analytics & Operations)',
    description: 'Diagnostic performance analytics, percentile rankings, subject-wise mastery curves, and personalized weak-area detection.',
    prismaModels: ['PerformanceMetric', 'SubjectMastery'],
    primaryApiRoutes: ['/api/v1/performance/summary', '/api/v1/performance/topics', '/api/v1/performance/trends'],
    primaryActors: ['STUDENT', 'TEACHER', 'ADMIN', 'PARENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Calculated asynchronously or cached via PerformanceMetric snapshots for sub-50ms dashboard response',
      'Subject mastery scores are computed via exponential moving average of recent attempts',
    ],
  },
  {
    id: 'reading-hour-mgmt',
    numericIndex: 7,
    name: 'Reading Hour Management',
    category: 'Analytics & Habits',
    phase: 'Phase 2 (Assessment & Tracking)',
    description: 'Curriculum reading goals, daily/weekly target minutes per batch, assigned literature, and teacher audit reviews.',
    prismaModels: ['ReadingTarget', 'ReadingLog'],
    primaryApiRoutes: ['/api/v1/reading/targets', '/api/v1/reading/audit', '/api/v1/reading/verify-log'],
    primaryActors: ['TEACHER', 'ADMIN', 'STUDENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Enforces institutional target of 60 mins/day or 300 mins/week',
      'Logs require teacher verification if submitted manually without verified timer heartbeats',
    ],
  },
  {
    id: 'reading-timer',
    numericIndex: 8,
    name: 'Reading Timer',
    category: 'Analytics & Habits',
    phase: 'Phase 2 (Assessment & Tracking)',
    description: 'Active client-side reading timer equipped with periodic server-side heartbeat verification, idle detection, and distraction logging.',
    prismaModels: ['ReadingSession', 'ReadingHeartbeat'],
    primaryApiRoutes: ['/api/v1/reading/timer/start', '/api/v1/reading/timer/heartbeat', '/api/v1/reading/timer/stop'],
    primaryActors: ['STUDENT'],
    mobileTarget: 'Offline-First',
    keyInvariants: [
      'Requires active heartbeat every 60 seconds; sessions with missing heartbeats are capped at last verified timestamp',
      'On mobile, handles app backgrounding using native background service timestamp diffing',
    ],
  },
  {
    id: 'student-dashboard',
    numericIndex: 9,
    name: 'Student Dashboard',
    category: 'Academic Core',
    phase: 'Phase 1 (Foundation)',
    description: 'Unified command center showing daily streak, upcoming exams, reading progress bar, pending assignments, and urgent notices.',
    prismaModels: ['StudentProfile', 'Notification', 'ReadingSession'],
    primaryApiRoutes: ['/api/v1/dashboard/student'],
    primaryActors: ['STUDENT', 'PARENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Consolidates 5 module metrics into a single lightweight JSON payload to minimize roundtrips on slow cellular connections',
    ],
  },
  {
    id: 'admin-panel',
    numericIndex: 10,
    name: 'Admin Panel',
    category: 'Administration',
    phase: 'Phase 1 (Foundation)',
    description: 'Institutional control panel for user provisioning, batch allocation, system configuration, and audit trail inspection.',
    prismaModels: ['Organization', 'AuditLog', 'User'],
    primaryApiRoutes: ['/api/v1/admin/stats', '/api/v1/admin/audit-logs', '/api/v1/admin/config'],
    primaryActors: ['SUPER_ADMIN', 'ADMIN'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Every administrative mutation produces an immutable AuditLog entry with IP address and actor ID',
    ],
  },
  {
    id: 'teacher-staff-mgmt',
    numericIndex: 11,
    name: 'Teacher/Staff Management',
    category: 'Administration',
    phase: 'Phase 1 (Foundation)',
    description: 'Faculty directory, subject qualifications, batch assignments, workload tracking, and pedagogical permissions.',
    prismaModels: ['TeacherProfile', 'StaffBatchAssignment', 'User'],
    primaryApiRoutes: ['/api/v1/staff', '/api/v1/staff/:id', '/api/v1/staff/assignments'],
    primaryActors: ['SUPER_ADMIN', 'ADMIN'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Staff cannot be unassigned from a batch while an active examination is in progress',
    ],
  },
  {
    id: 'attendance',
    numericIndex: 12,
    name: 'Attendance',
    category: 'Academic Core',
    phase: 'Phase 3 (Analytics & Operations)',
    description: 'Daily and session-based attendance tracking, batch rolls, leave management, and automated absent alerts.',
    prismaModels: ['AttendanceRecord', 'Batch'],
    primaryApiRoutes: ['/api/v1/attendance/mark', '/api/v1/attendance/batch', '/api/v1/attendance/student'],
    primaryActors: ['TEACHER', 'ADMIN', 'STUDENT', 'PARENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Attendance records are immutable once locked by the end of the academic day',
      'Triggers automated notification to parents upon unexcused absence',
    ],
  },
  {
    id: 'notifications',
    numericIndex: 13,
    name: 'Notifications',
    category: 'Platform Services',
    phase: 'Phase 1 (Foundation)',
    description: 'Multi-channel messaging hub delivering in-app badges, exam countdown alerts, reading goal reminders, and future push notifications.',
    prismaModels: ['Notification', 'User'],
    primaryApiRoutes: ['/api/v1/notifications', '/api/v1/notifications/read', '/api/v1/notifications/broadcast'],
    primaryActors: ['STUDENT', 'TEACHER', 'ADMIN', 'PARENT', 'SUPER_ADMIN'],
    mobileTarget: 'Online Real-Time',
    keyInvariants: [
      'Supports batch fan-out to all students in a batch with a single database insert or background job',
    ],
  },
  {
    id: 'reports',
    numericIndex: 14,
    name: 'Reports',
    category: 'Platform Services',
    phase: 'Phase 3 (Analytics & Operations)',
    description: 'Automated generation of institutional grade cards, attendance rosters, reading habit audits, and CSV/PDF data exports.',
    prismaModels: ['ReportAudit'],
    primaryApiRoutes: ['/api/v1/reports/grade-card', '/api/v1/reports/attendance-summary', '/api/v1/reports/reading-audit'],
    primaryActors: ['ADMIN', 'TEACHER', 'PARENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Report generation queries read replicas or prepared cached views to prevent locking transaction tables',
    ],
  },
  {
    id: 'payments-subscriptions',
    numericIndex: 15,
    name: 'Future Payments/Subscriptions',
    category: 'Platform Services',
    phase: 'Phase 4 (Enterprise & Payments)',
    description: 'Tiered subscription billing, course fees, payment gateway webhook listeners, invoice history, and access entitlement state machines.',
    prismaModels: ['SubscriptionPlan', 'Subscription'],
    primaryApiRoutes: ['/api/v1/billing/plans', '/api/v1/billing/checkout', '/api/v1/billing/webhook'],
    primaryActors: ['SUPER_ADMIN', 'ADMIN', 'PARENT'],
    mobileTarget: 'Standard Read/Write',
    keyInvariants: [
      'Designed to interface with Stripe or local payment gateways via idempotent webhook processing',
      'Grace period handling prevents immediate lockout of active exam access on failed renewal',
    ],
  },
];
